POST http://localhost:2525/imposters
Content-Type: application/json

{
  "port": 5015,
  "protocol": "http",
  "name": "get_fallback",
  "stubs": [
    {
      "predicates": [
        {
          "equals": {
            "method": "GET"
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 404,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "error": "not_found",
              "message": "O recurso solicitado não existe."
            }
          }
        }
      ]
    }
  ]
}