POST http://localhost:2525/imposters
Content-Type: application/json

{
  "port": 5008,
  "protocol": "http",
  "name": "temperature_validation",
  "stubs": [
    {
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/api/temperature",
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "not": {
            "contains": {
              "body": "\"value\""
            }
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 400,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "error": "missing_field",
              "message": "O campo 'value' é obrigatório."
            }
          }
        }
      ]
    }
  ]
}